name = "Piqs"
uuid = "18c821f0-cbdb-4973-8466-97967e7790ff"
authors = ["Yanis Le Fur"]
version = "1.0.0-DEV"

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"

[compat]
DiffEqCallbacks = "4.3.0"
QuantumToolbox = "0.29.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
