name = "Piqs"
uuid = "18c821f0-cbdb-4973-8466-97967e7790ff"
authors = ["Yanis Le Fur"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
