name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'  # Or your preferred version

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(path=".")
            Pkg.instantiate()
          '

      - name: Build and deploy docs
        run: julia --project=docs docs/make.jl
